# Generated by Django 5.0 on 2024-05-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('stargazers_count', models.IntegerField()),
                ('forks', models.IntegerField()),
            ],
        ),
    ]
